INSERT INTO demande_acte_naissance (
        citoyen_id,
        agent_id,
        nom_enfant,
        nom_pere,
        nom_mere,
        date_naissance,
        lieu_naissance,
        statut,
        certificat_medical,
        photo_url
    )
VALUES (
        1,
        6,
        'Moussa',
        'Diallo',
        'Sow',
        '2024-04-01',
        'Conakry',
        'valide',
        'certif1.pdf',
        'photo1.jpg'
    ),
    (
        1,
        6,
        'Fatoumata',
        'Keita',
        'Bah',
        '2023-09-10',
        'Kindia',
        'en_attente',
        'certif2.pdf',
        'photo2.jpg'
    ),
    (
        1,
        6,
        'Ibrahima',
        'Barry',
        'Sylla',
        '2023-12-25',
        'Labé',
        'refuse',
        'certif3.pdf',
        'photo3.jpg'
    ),
    (
        1,
        6,
        'Mariama',
        'Camara',
        'Cissé',
        '2022-07-15',
        'Nzérékoré',
        'en_attente',
        'certif4.pdf',
        'photo4.jpg'
    ),
    (
        1,
        6,
        'Amadou',
        'Bangoura',
        'Kourouma',
        '2024-01-20',
        'Kankan',
        'valide',
        'certif5.pdf',
        'photo5.jpg'
    );